
name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: ha-ha
        uses: ./.github/actions/joke-action
